# Generated by Django 5.1.7 on 2025-03-28 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='garage.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('notification_date', models.DateTimeField()),
                ('notification_type', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateTimeField()),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='repairs', to='garage.technician')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='repairs', to='garage.vehicle')),
            ],
        ),
    ]
