# Generated by Django 5.1.7 on 2025-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_maintenance_maintenance_date_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='user_id',
            new_name='owner',
        ),
    ]
