# Generated by Django 5.1.7 on 2025-03-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_rename_user_id_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
