# Generated by Django 5.1.7 on 2025-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_vehicle_make_alter_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='phone_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
