# Generated by Django 5.1.7 on 2025-04-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_alter_technician_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetype',
            name='maintenance_type_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
