# Generated by Django 5.1.7 on 2025-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_maintenancetype_maintenance_type_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='maintenance_type_desc',
            field=models.TextField(null=True),
        ),
    ]
