# Generated by Django 5.1.7 on 2025-04-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_maintenancetype_maintenance_type_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetype',
            name='maintenance_type_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
