# Generated by Django 5.1.7 on 2025-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_alter_vehicle_make_alter_vehicle_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='mileage_type',
            new_name='mileage',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_type',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_types',
            field=models.ManyToManyField(related_name='maintenances', to='garage.maintenancetype'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='miscellaneous_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
