# Generated by Django 5.1.7 on 2025-04-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_rename_mileage_type_maintenance_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_types',
            field=models.ManyToManyField(blank=True, related_name='maintenances', to='garage.maintenancetype'),
        ),
    ]
