# Generated by Django 5.1.7 on 2025-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0014_alter_repair_description_alter_repair_repair_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Is_read',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_date',
            field=models.DateField(null=True),
        ),
    ]
