# Generated by Django 5.1.7 on 2025-04-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0016_alter_repair_repair_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_id',
        ),
    ]
