# Generated by Django 5.1.7 on 2025-04-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0017_remove_appointment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='open', max_length=100),
        ),
    ]
